### ISSUE TITLE
Problem with use classMap and ArrayHelper

### ISSUE THREAD

**Issue by johnluxor** [janisto/yii2-environment#1]
When I create my own ArrayHelper and try to use it through classMap it doesn't work because ArrayHelper is used in Environment and include before classMap is used. 

The solve is  create one more Merge method in child class was extended from Environment and replace getConfig() and setup() methods to use my merge method

**Comment by janisto** [comment]
Do you really need to use your own ArrayHelper to merge two arrays in Environment class?

**Comment by cebe** [comment]
if arrayhelper is autoloaded once it is using the same class for the whole request. @johnluxor how did you configure the classmap? Should work if you do it in index.php before Environment is used.

**Comment by johnluxor** [comment]
@cebe  'yii\helpers\ArrayHelper' => '@app/helpers/ArrayHelper.php' - it's element in classMap array in config file. I can't set Yii::$classMap before use Environment because Environment::setup() include Yii.php file and only after that I can do it

@janisto  I use my own ArrayHelper in my code. I added there some methods. And because of Environment::$classMap merge with Yii::$classmap after autoload I can't use my own ArrayHelper

**Comment by johnluxor** [comment]
@janisto  I added protected method  merge in extended Environment

**Comment by janisto** [comment]
Did you try to add ArrayHelper to classMap with full path without @app alias?

**Comment by janisto** [comment]
Like this:

```
'yii\helpers\ArrayHelper' =>  dirname(__DIR__) . '/helpers/ArrayHelper.php'
```

**Comment by janisto** [comment]
I guess I could add a protected merge method to Environment class, so it would be easier to extend and override it.

**Comment by johnluxor** [comment]
@janisto Yes I have tried a lot of ways to write path )

It will be great ) Thank you.

And I want to ask. In old version was abilities to use 'inherit' for example in console config, when I use the same parameters. Have you any plans to add it again?

**Comment by janisto** [comment]
New release added, just extend Environment and override the merge method.

I really don't like the 'inherit' feature, so most likely it won't be implemented.
